- name: install packages
  sudo: yes
  yum:
    name: "{{ item.name }}"
    enablerepo: "{{ item.enablerepo }}"
    state: present
  with_items: zabbix_server_install_packages

- name: ensure started zabbix-server
  sudo: yes
  service:
    name: zabbix-server
    state: started
    enabled: yes

- name: configure zabbix-server.conf
  sudo: yes
  template:
    dest: /etc/zabbix/zabbix_server.conf
    src: zabbix_server.conf.j2
    owner: root
    group: zabbix
    mode: 0640
  notify: restart zabbix-server
